### ISSUE TITLE
editable format?

### ISSUE THREAD

**Issue by laf0rge** [nickel0/3GPP-Overall-Architecture#1]
first of all, thanks again for creating that diagram, I think it is an excellent resource.

I would like to suggest to publish it in some editable format.  I'm not sure what kind of program you used to create it, but the native file of that program would be the precondition of allowing other people to contribute / extend this in the future.

**Comment by nickel0** [comment]
Thank you for your advise. I've uploaded the original editable pptx file. Now everyone can contribute the work in the future.
