### ISSUE TITLE
missing license for this work

### ISSUE THREAD

**Issue by laf0rge** [nickel0/3GPP-Overall-Architecture#2]
Unfortunately the repository doesn't state the license of the diagram.  This is important to know if other people are allowed to use this diagram. You could e.g. choose one of the CC (creative comons) licenses, such as CC-BY-SA which would mean
* people can use this diagram (or derivatives of it)
* they always have to mention you as the author/source
* any derivative works also must be released under the same conditions.

But of course you could also go for something ore permissive, as you like.

**Comment by nickel0** [comment]
Thank you for your comments about license.
I've choosed to adapt the CC BY-NC-SA 4.0 license to this work.
